import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { iconRegistry } from "./iconRegistry";

describe("iconRegistry", () => {
  // Saved maps store the id as properties.iconName, so a renamed or dropped id
  // blanks that icon on every map that placed it. The ids are Phosphor
  // component names from before the PheedLoop swap (ENG-3918) and stay that way.
  it("keeps every id a saved map can reference", () => {
    expect(iconRegistry.map(entry => entry.id)).toEqual([
      "PiToilet",
      "PiWheelchair",
      "PiElevator",
      "PiStairs",
      "PiCar",
      "PiDoor",
      "PiTrash",
      "PiRecycle",
      "PiFirstAid",
      "PiFireExtinguisher",
      "PiWarning",
      "PiShield",
      "PiInfo",
      "PiCamera",
      "PiForkKnife",
      "PiCoffee",
      "PiWifiHigh",
      "PiPlug",
      "PiMicrophone",
      "PiPhone",
      "PiEnvelope",
      "PiPrinter",
      "PiTicket",
      "PiGift",
      "PiArrowRight",
      "PiMapPin",
      "PiStar",
      "PiFlag",
      "PiSignpost",
      "PiTree",
      "PiFlower",
      "PiDog",
      "PiDrop",
      "PiMusicNote",
      "PiSpeakerHigh",
      "PiMonitor",
      "PiPresentation",
      "PiLightning",
      "PiCarBattery",
      "PiThermometer",
      "PiSquare",
      "PiCircle",
      "PiTriangle",
      "PiHeart",
      "PiDiamond",
      "PiLock",
      "PiKey",
      "PiClock",
      "PiCalendar",
      "PiBell",
      "PiBicycle",
      "PiBus",
      "PiTaxi",
      "PiTrain",
      "PiAirplaneTakeoff",
      "PiHouse",
      "PiBuildings",
      "PiTent",
      "PiPark",
      "PiSun",
      "PiMoon",
      "PiCloudRain",
      "PiSnowflake",
      "PiWind",
      "PiBaby",
      "PiHandshake",
      "PiUsers",
      "PiUserCircle",
      "PiMegaphone",
      "PiShoppingCart",
      "PiTShirt",
      "PiBackpack",
      "PiSuitcase",
      "PiGameController",
      "PiBalloon",
      "PiConfetti",
      "PiCrown",
      "PiRocket",
      "PiAlien",
      "PiGhost",
      "PiSkull",
      "PiCat",
      "PiHamburger",
      "PiPizza",
      "PiBeerBottle",
      "PiWine",
      "PiCookingPot",
      "PiScissors",
      "PiPaintBrush",
      "PiPencil",
      "PiNotebook",
      "PiMedal",
      "PiTrophy",
      "PiTarget",
      "PiSoccerBall",
      "PiGlobe",
      "PiCompass",
      "PiBinoculars",
      "PiMountains",
    ]);
  });

  it("draws every icon in the colour it is given", () => {
    for (const entry of iconRegistry) {
      const svg = renderToStaticMarkup(
        createElement(entry.component, { size: 128, color: "#123456" }),
      );
      expect(svg, entry.id).toContain("#123456");
    }
  });
});
